[package]
name = "win_socket_command"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
linereader = "0.4.0"
websocket = { version = "0.27.0", default-features = false, features = ["sync"] }
